import Button from "../../../components/ui/Button";
import Spinner from "../../../components/ui/spinner/spinner";

const AutoGeneratedChart = ({ chartData, onConfirm, onEdit }) => {
  if (!chartData) {
    return (
      <div className="w-full flex flex-col items-center justify-center min-h-[20rem]">
        <Spinner />
        <p className="mt-4 text-gray-500">Generating your charts...</p>
      </div>
    );
  }

  const rasiChartData = chartData.rasi_chart;
  const navamsaChartData = chartData.navamsa_chart;

  const handleConfirmClick = () => {
    onConfirm(chartData);
  };

  return (
    <div className="w-full flex flex-col items-center">
      <div className="flex flex-col md:flex-row gap-12">
        <ChartGrid title="Rasi Chart" data={rasiChartData} />
        <ChartGrid title="Navamsa Chart" data={navamsaChartData} />
      </div>
      <div className="flex items-center gap-4 mt-10">
        <Button
          label="Edit"
          size="auth"
          color="purpleBorder"
          onClick={onEdit}
          className="bg-gray-100"
        />
        <Button
          label="Confirm"
          size="auth"
          color="purple"
          onClick={handleConfirmClick}
        />
      </div>
    </div>
  );
};

export default AutoGeneratedChart;

const Square = ({ num, planets }) => (
  <div className="relative w-16 h-16 bg-purple rounded-md flex items-start justify-start p-1 text-xs text-white">
    <span className="absolute top-1 right-1 opacity-70">{num}</span>
    <div className="absolute bottom-1 left-1 flex flex-col items-start gap-0.5">
      {planets?.map((planet, index) => (
        <span key={index} className="text-[10px] leading-none">
          {planet}
        </span>
      ))}
    </div>
  </div>
);

const BigSquare = ({ title }) => (
  <div className="col-span-2 row-span-2 w-[calc(100% + 0.5rem)] h-[calc(100% + 0.5rem)] bg-purple rounded-md flex items-center justify-center text-white text-sm text-center p-2">
    {title}
  </div>
);

const ChartGrid = ({ title, data }) => {
  const getPlanets = (place) => data?.[`place${place}`] || [];

  return (
    <div className="grid grid-cols-[repeat(4,4rem)] grid-rows-[repeat(4,4rem)] gap-2">
      <Square num="01" planets={getPlanets(1)} />
      <Square num="02" planets={getPlanets(2)} />
      <Square num="03" planets={getPlanets(3)} />
      <Square num="04" planets={getPlanets(4)} />
      <Square num="12" planets={getPlanets(12)} />
      <BigSquare title={title} />
      <Square num="05" planets={getPlanets(5)} />
      <Square num="11" planets={getPlanets(11)} />
      <Square num="06" planets={getPlanets(6)} />
      <Square num="10" planets={getPlanets(10)} />
      <Square num="09" planets={getPlanets(9)} />
      <Square num="08" planets={getPlanets(8)} />
      <Square num="07" planets={getPlanets(7)} />
    </div>
  );
};
