import Button from "../../../components/ui/Button";

const Square = ({ num, planet, detail }) => (
  <div className="relative w-16 h-16 bg-darkRed rounded-md flex items-start justify-start text-xs text-white">
    <span className="absolute top-1 right-1 opacity-70">{num}</span>
    <div className="absolute bottom-1 left-1 flex flex-col">
      <span>{planet}</span>
      <span className="text-[10px] opacity-80">{detail}</span>
    </div>
  </div>
);

const BigSquare = ({ title }) => (
  <div className="col-span-2 row-span-2 w-[calc(100% + 0.5rem)] h-[calc(100% + 0.5rem)] bg-darkRed rounded-md flex items-center justify-center text-white text-sm">
    {title}
  </div>
);

const ChartGrid = ({ title }) => (
  <div className="grid grid-cols-[repeat(4,4rem)] grid-rows-[repeat(4,4rem)] gap-2">
    {/* Top row */}
    <Square num="01" planet="Ma" detail="Guru" />
    <Square num="02" />
    <Square num="03" planet="Ma" detail="Guru" />
    <Square num="04" />
    {/* Second row */}
    <Square num="12" planet="Ma" detail="Guru" />
    <BigSquare title={title} />
    <Square num="05" />
    {/* Third row */}
    <Square num="11" />
    <Square num="06" planet="Ma" detail="Guru" />
    {/* Bottom row */}
    <Square num="10" planet="Ma" detail="Guru" />
    <Square num="09" />
    <Square num="08" planet="Ma" detail="Guru" />
    <Square num="07" />
  </div>
);

const AutoGeneratedChart = ({ onConfirm, onEdit }) => {
  return (
    <div className="w-full flex flex-col items-center">
      <div className="flex flex-col md:flex-row gap-12">
        <ChartGrid title="Rasi Chart" />
        <ChartGrid title="Navamsa Chart" />
      </div>

      <div className="flex items-center gap-4 mt-10">
        <Button
          label="Edit"
          size="auth"
          color="darkRedBorder"
          onClick={onEdit}
          className="bg-gray-100"
        />
        <Button
          label="Confirm"
          size="auth"
          color="darkRed"
          onClick={onConfirm}
        />
      </div>
    </div>
  );
};

export default AutoGeneratedChart;
