import { useEffect, useRef } from "react";
import { useSearchParams } from "react-router-dom";
import Stepper from "../../../components/ui/stepper/Stepper";
import Step1Form from "./Step1Form";
import Step2Form from "../cp2/Step2Form";
import Step3Form from "../cp3/CompleteProfile3";
import GenerateChartForm from "../cp2/GenerateChartForm";
import AutoGeneratedChart from "../cp2/AutoGenerateChart";
import ManualEntryForm from "../cp2/ManualEntryForm";
import ManualChartEditor from "../cp2/manualchart/ManualChartEditor";
import { useUIState } from "../../../context/UIStateContext";
import {
  saveUserData,
  updateUserData,
} from "../../../services/completeProfileApi/completeProfileApi";
import { docId } from "../../../data/Data";
import { useUserProfile } from "../../../hooks/swr/useUserProfile";
import Spinner from "../../../components/ui/spinner/spinner";

const CompleteProfile = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const currentStep = parseInt(searchParams.get("step")) || 1;
  const step2View = searchParams.get("view") || "choice";
  const totalSteps = 3;
  // const [editorKey, setEditorKey] = useState(0);
  const { setLoading, setApiError } = useUIState();
  const {
    profile,
    isLoading: isProfileLoading,
    isValidating,
    isError,
    mutate,
  } = useUserProfile(docId);
  const chartEditorRef = useRef(null);

  useEffect(() => {
    if (currentStep === 2 && step2View === "manualform") {
      mutate();
    }
  }, [currentStep, step2View, mutate]);

  const goTo = (params) => {
    setSearchParams(params);
  };

  const handleStep1Submit = async (data) => {
    setLoading(true);
    setApiError(null);

    const payload = {
      docId: docId,
      personalDetails: {
        first_name: data.firstName,
        last_name: data.lastName,
        full_name: `${data.firstName} ${data.lastName}`,
        gender: data.gender,
      },
    };
    try {
      const response = await saveUserData(payload);
      console.log("Step 1 data:", response);
      goTo({ step: "2", view: "choice" });
    } catch (error) {
      console.error("API Error:", error);
      setApiError("Failed to save profile. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleStep2ChoiceSubmit = (selection) => {
    console.log("Step 2 Choice:", selection);
    if (selection.inputMethod === "manual") {
      goTo({ step: "2", view: "manualform" });
    } else if (selection.inputMethod === "generate") {
      goTo({ step: "2", view: "generate" });
    }
  };

  const handleGenerateFormSubmit = (data) => {
    console.log("Generate Chart Data:", data);
    goTo({ step: "2", view: "showChart" });
  };

  const handleChartConfirm = () => {
    console.log("Chart Confirmed");
    goTo({ step: "3" });
  };

  const handleChartEdit = () => {
    console.log("Editing Chart Details - Resetting planets...");
    if (chartEditorRef.current) {
      chartEditorRef.current.resetPlanets();
    }
  };

  const handleManualEntryFormSubmit = async (data) => {
    setLoading(true);
    setApiError(null);
    const formattedTime = `${data.timeOfBirth}:00`;

    const payload = {
      docId: docId,
      astrology: {
        rasi: data.rasi.value,
        natchathiram: data.natchathiram.value,
        dob: data.dateOfBirth,
        dot: formattedTime,
        birth_location: data.placeOfBirth.value,
      },
    };
    try {
      if (profile && profile.astrology) {
        await updateUserData(payload);
      } else {
        console.log("Saving new astrology data...");
        await saveUserData(payload);
      }
      goTo({ step: "2", view: "numberedChart" });
    } catch (error) {
      console.error("API Error:", error);
      setApiError("Failed to save profile. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleStep3Submit = (data) => {
    console.log("Final Profile Data:", data);
  };

  const renderStepHeader = () => {
    switch (currentStep) {
      case 1:
        return (
          <div>
            <p className="text-middleGray font-medium">Enter the details</p>
            <p className="font-bold text-purple text-lg">
              to complete your profile
            </p>
          </div>
        );
      case 2:
        if (step2View === "generate") {
          return (
            <div>
              <p className="text-middleGray font-medium">Enter birth details</p>
              <p className="font-bold text-purple text-lg">
                to calculate Astrology chart
              </p>
            </div>
          );
        } else if (step2View === "showChart") {
          return (
            <div>
              <p className="font-bold text-purple">
                This is your Rasi, Navamsa chart
              </p>
              <p className="text-sm text-middleGray">
                If any changes, you can edit. Otherwise confirm it.
              </p>
            </div>
          );
        } else if (
          step2View === "manualform" ||
          step2View === "numberedChart"
        ) {
          return (
            <div>
              <p className="text-middleGray font-medium">Enter birth details</p>
              <p className="font-bold text-purple text-lg">
                to calculate Astrology chart
              </p>
            </div>
          );
        } else {
          return (
            <div>
              <p className="text-middleGray font-medium">Choose preferred</p>
              <p className="font-bold text-purple text-lg">
                Astrology chart input method
              </p>
              <p className="text-middleGray text-sm">
                You can generate astrology chart with required birth details or
                you can enter manually
              </p>
            </div>
          );
        }
      case 3:
        return (
          <div>
            <p className="text-middleGray">Enter the personal details</p>
            <p className="font-bold text-purple text-lg">
              to complete your profile
            </p>
          </div>
        );
      default:
        return null;
    }
  };

  const renderStepContent = () => {
    switch (currentStep) {
      case 1:
        return <Step1Form onSubmit={handleStep1Submit} />;
      case 2:
        switch (step2View) {
          case "generate":
            return <GenerateChartForm onSubmit={handleGenerateFormSubmit} />;
          case "showChart":
            return (
              <AutoGeneratedChart
                onConfirm={handleChartConfirm}
                onEdit={() => goTo({ step: "2", view: "generate" })}
              />
            );
          case "manualform":
            if (isValidating) {
              return <Spinner />;
            } else if (isError) {
              return <p className="text-red-500">Something went wrong</p>;
            }
            return (
              <ManualEntryForm
                onSubmit={handleManualEntryFormSubmit}
                existingData={profile?.astrology}
              />
            );
          case "numberedChart":
            return (
              <ManualChartEditor
                key={chartEditorRef}
                title="Rasi"
                onConfirm={handleChartConfirm}
                onEdit={handleChartEdit}
              />
            );
          case "choice":
          default:
            return <Step2Form onSubmit={handleStep2ChoiceSubmit} />;
        }
      case 3:
        return <Step3Form onSubmit={handleStep3Submit} />;
      default:
        return <Step1Form onSubmit={handleStep1Submit} />;
    }
  };

  return (
    <div className="flex flex-col">
      <div className="flex-grow">
        <div className="px-6">
          <div className="pt-14 pb-8 text-center">{renderStepHeader()}</div>
          <div className="w-full mb-6">
            <Stepper currentStep={currentStep} totalSteps={totalSteps} />
          </div>
          <div>{renderStepContent()}</div>
        </div>
      </div>
    </div>
  );
};

export default CompleteProfile;
