export const rasiOptions = [
  { value: "Aries", label: "Aries" },
  { value: "Taurus", label: "Taurus" },
  { value: "Gemini", label: "Gemini" },
  { value: "Cancer", label: "Cancer" },
  { value: "Leo", label: "Leo" },
  { value: "Virgo", label: "Virgo" },
  { value: "Libra", label: "Libra" },
  { value: "Scorpio", label: "Scorpio" },
  { value: "Sagittarius", label: "Sagittarius" },
  { value: "Capricorn", label: "Capricorn" },
  { value: "Aquarius", label: "Aquarius" },
  { value: "Pisces", label: "Pisces" },
];

export const starOptions = [
  { value: "Ashwini", laSwatibel: "Ashwini" },
  { value: "Bharni", label: "Bharni" },
  { value: "Krittika", label: "Krittika" },
  { value: "Rohini", label: "Rohini" },
  { value: "Mirugasheeridam", label: "Mrigshira" },
  { value: "Ardra", label: "Thiruvathirai" },
  { value: "Punarvasu", label: "Punarpusham" },
  { value: "Pushya", label: "Poosham" },
  { value: "Ashlesha", label: "Aayilyam" },
  { value: "Magha", label: "Magham" },
  { value: "Purvaphalguni", label: "Pooram" },
  { value: "Uttraphalguni", label: "Uththaram" },
  { value: "Hasta", label: "Ashththam" },
  { value: "Chitra", label: "Chitrai" },
  { value: "Swati", label: "Swathi" },
  { value: "Vishakha", label: "Vishakham" },
  { value: "Anuradha", label: "Anusham" },
  { value: "Jyeshtha", label: "Keddai" },
  { value: "Mool", label: "Moolam" },
  { value: "Purvashadha", label: "Pooradam" },
  { value: "Uttrashadha", label: "Uththaradam" },
  { value: "Shravan", label: "Thiruvonam" },
  { value: "Dhanishtha", label: "Aviddam" },
  { value: "Shatbhishvishakhaa", label: "Sathayam" },
  { value: "Purvabhadrapad", label: "Pooraddaathi" },
  { value: "Uttvishakharabhadrapad", label: "Uththaraddathi" },
  { value: "Revati", label: "Revathi" },
];

export const PLANETS = [
  { id: "sun", name: "Sun", tamil: "சூரியன்" },
  { id: "moon", name: "Moon", tamil: "சந்திரன்" },
  { id: "mars", name: "Mars", tamil: "செவ்வாய்" },
  { id: "mercury", name: "Mercury", tamil: "புதன்" },
  { id: "jupiter", name: "Jupiter", tamil: "குரு" },
  { id: "venus", name: "Venus", tamil: "சுக்கிரன்" },
  { id: "saturn", name: "Saturn", tamil: "சனி" },
  { id: "rahu", name: "Rahu", tamil: "ராகு" },
  { id: "ketu", name: "Ketu", tamil: "கேது" },
];
