export const rasiOptions = [
  { value: "mesha", label: "Mesha (Aries)" },
  { value: "vrishabha", label: "Vrishabha (Taurus)" },
  { value: "mithuna", label: "Mithuna (Gemini)" },
  { value: "karka", label: "Karka (Cancer)" },
  { value: "simha", label: "Simha (Leo)" },
  { value: "kanya", label: "Kanya (Virgo)" },
  { value: "tula", label: "Tula (Libra)" },
  { value: "vrishchika", label: "Vrishchika (Scorpio)" },
  { value: "dhanu", label: "Dhanu (Sagittarius)" },
  { value: "makara", label: "Makara (Capricorn)" },
  { value: "kumbha", label: "Kumbha (Aquarius)" },
  { value: "meena", label: "Meena (Pisces)" },
];

export const starOptions = [
  { value: "ashwini", label: "Ashwini" },
  { value: "bharani", label: "Bharani" },
  { value: "krittika", label: "Krittika" },
  { value: "rohini", label: "Rohini" },
  { value: "mrigashira", label: "Mrigashira" },
  { value: "ardra", label: "Ardra" },
  { value: "punarvasu", label: "Punarvasu" },
  { value: "pushya", label: "Pushya" },
  { value: "ashlesha", label: "Ashlesha" },
  { value: "magha", label: "Magha" },
  { value: "purva_phalguni", label: "Purva Phalguni" },
  { value: "uttara_phalguni", label: "Uttara Phalguni" },
  { value: "hasta", label: "Hasta" },
  { value: "chitra", label: "Chitra" },
  { value: "swati", label: "Swati" },
  { value: "vishakha", label: "Vishakha" },
  { value: "anuradha", label: "Anuradha" },
  { value: "jyeshtha", label: "Jyeshtha" },
  { value: "mula", label: "Mula" },
  { value: "purva_ashadha", label: "Purva Ashadha" },
  { value: "uttara_ashadha", label: "Uttara Ashadha" },
  { value: "shravana", label: "Shravana" },
  { value: "dhanishta", label: "Dhanishta" },
  { value: "shatabhisha", label: "Shatabhisha" },
  { value: "purva_bhadrapada", label: "Purva Bhadrapada" },
  { value: "uttara_bhadrapada", label: "Uttara Bhadrapada" },
  { value: "revati", label: "Revati" },
];

export const PLANETS = [
  { id: "sun", name: "Sun", tamil: "சூரியன்" },
  { id: "moon", name: "Moon", tamil: "சந்திரன்" },
  { id: "mars", name: "Mars", tamil: "செவ்வாய்" },
  { id: "mercury", name: "Mercury", tamil: "புதன்" },
  { id: "jupiter", name: "Jupiter", tamil: "குரு" },
  { id: "venus", name: "Venus", tamil: "சுக்கிரன்" },
  { id: "saturn", name: "Saturn", tamil: "சனி" },
  { id: "rahu", name: "Rahu", tamil: "ராகு" },
  { id: "ketu", name: "Ketu", tamil: "கேது" },
];
